### ISSUE TITLE
renaming to Guard uniquely 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [jiachengzhang1/Umbrella.jl#1]
I have a few recommendations before we register this. Adding `.jl` suffix

Also, there exists a package with a similar name: https://github.com/JuliaActors/Guards.jl

We can rename it `JackGuard.jl` `ProcGuard.jl` `AuthGuard.jl` so it's indexed on Google search Engine and shown in top results 🗡️ 👯‍♂️

**Comment by jiachengzhang1** [comment]
how about `Umbrella.jl`?

**Comment by AbhimanyuAryan** [comment]
Hahaha sounds cool
